version: "3"
services:
  app:
    build: ./
    environment:
      - DATABASE_URL=postgres://semiquaver:smq.moe@db:5432/semiquaver
      - SESSION_SECRET=38247819234890172347823
      - FRONTEND=https://localhost:5000
      - NODE_ENV=development
    ports:
      - "8585:8585"
    volumes:
      - ./migrations:/app/migrations
    links:
      - db
      - redis
  db:
    build: docker-db/
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=semiquaver
      - POSTGRES_PASSWORD=smq.moe
      - POSTGRES_DB=semiquaver
    volumes:
      - dbdata:/var/lib/postgresql/data
  redis:
    image: redis:3
volumes:
  dbdata:
